blank_issues_enabled: true
contact_links:
  - name: ğŸ’¡ Feature requests
    url: https://github.com/biomejs/biome-vscode/discussions/new
    about: Please use a new GitHub discussion to propose ideas of feature requests.
  - name: ğŸ—£ï¸ Chat
    url: https://discord.gg/BypW39g6Yc
    about: Our Discord server is active and is used for real-time discussions including contribution collaboration, questions, and more!
  - name: ğŸ†˜ Support
    url: https://discord.gg/BypW39g6Yc
    about: "For assistance, please use the #help channel on our Discord community."
