# This workflow is responsible for publishing a stable release of the extension
# to the Visual Studio Marketplace, the Open VSX Registry, and GitHub Releases.
# It is triggered automatically whenever a new semver-compliant stable tag is 
# pushed to the repository.

name: ~Publish stable release

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
        description: The version of the extension to publish

jobs:
  package:
    name: Package
    uses: ./.github/workflows/~package-stable.yaml
    secrets: inherit
  publish-to-github-releases:
    needs: [package]
    name: Publish to GitHub Releases
    uses: ./.github/workflows/~publish-to-github-releases.yaml
    secrets: inherit
    with:
      version: ${{ inputs.version }}
      channel: stable
  # publish-to-vs-marketplace:
  #   needs: [package]
  #   name: Publish to Visual Studio Marketplace
  #   uses: ./.github/workflows/~publish-to-vs-marketplace.yaml
  #   with:
  #     channel: stable
  # publish-to-ovsx-registry:
  #   needs: [package]
  #   name: Publish to Visual Studio Marketplace
  #   uses: ./.github/workflows/~publish-to-ovsx-registry.yaml
  #   with:
  #     channel: stable
    